apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  ports:
    - port: 4000
      protocol: TCP
  selector:
    app: server
#  type: LoadBalancer
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: backend-ssl
 namespace: production
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: a@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: backend-ssl
   # Enable the HTTP-01 challenge provider
   solvers:
   - selector: {}
     http01:
       ingress:
         class:  nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "backend-ssl"
spec:
  rules:
  - host: backend.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: backend-service
          servicePort: 4000

  tls:
  - hosts:
    - backend.rafifauz.site
    secretName: backend-tls
