apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: production
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo:4.0.4
      ports:
        - containerPort: 27017
          name: mongodb-port
